
- hosts: all
  user: root
  sudo: yes
  vars:
    version: 1
  tasks:
  - apt_repository: repo='ppa:dotcloud/lxc-docker'
  - apt: update_cache=yes
  - name: add package $item
    apt: pkg=$item state=installed
    with_items:
    - vim
    - tmux
    - git-core
    - build-essential
    - python-setuptools
    - locate
    - openjdk-7-jdk
    - software-properties-common
    - linux-image-extra-$LOOKUP(pipe,uname -r)
    - lxc-docker
  - git: repo=https://github.com/dotcloud/docker-py.git dest=~/docker-py
  - shell: cd ~/docker-py && touch installed.{{version}} && sudo python setup.py install creates=~/docker-py/installed.{{version}}
  - get_url: url=https://raw.github.com/jlewallen/docker-ansible/master/docker-ansible.py dest=/usr/share/ansible/docker mode=0770
